package me.semmmetje.banditteams.command;

import me.semmmetje.banditteams.BanditTeams;
import me.semmmetje.banditteams.listener.TeamGui;
import me.semmmetje.banditteams.storage.Team;
import me.semmmetje.banditteams.util.Text;
import org.bukkit.Bukkit;
import org.bukkit.OfflinePlayer;
import org.bukkit.command.*;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.AsyncPlayerChatEvent;
import java.util.*;

public final class TeamCommand implements CommandExecutor, TabCompleter, Listener {
  private record Invite(UUID inviter,String team,long expiresAt){} private record Request(UUID player,long expiresAt){}
  private final BanditTeams plugin; private final Map<UUID,Invite> invites=new HashMap<>(); private final Map<String,Map<UUID,Request>> requests=new HashMap<>(); private final Set<UUID> creating=new HashSet<>(); private final Set<UUID> teamChatUsers=Collections.synchronizedSet(new HashSet<>());
  public TeamCommand(BanditTeams plugin){this.plugin=plugin;}
  public void beginCreate(Player player){if(plugin.teams().teamOf(player.getUniqueId())!=null){msg(player,"already-in-team",Map.of());return;}creating.add(player.getUniqueId());msg(player,"create-chat",Map.of());}
  @EventHandler public void chat(AsyncPlayerChatEvent event){Player player=event.getPlayer();if(creating.remove(player.getUniqueId())){event.setCancelled(true);String name=event.getMessage().trim();Bukkit.getScheduler().runTask(plugin,()->create(player,name));return;}if(!teamChatUsers.contains(player.getUniqueId()))return;Team team=plugin.teams().teamOf(player.getUniqueId());if(team==null||!team.teamChatEnabled()){teamChatUsers.remove(player.getUniqueId());return;}event.setCancelled(true);String message=event.getMessage();Bukkit.getScheduler().runTask(plugin,()->sendTeamChat(player,team,message));}
  @Override public boolean onCommand(CommandSender sender,Command command,String label,String[] args){if(!(sender instanceof Player player)){msg(sender,"player-only",Map.of());return true;}if(!player.hasPermission("banditteams.use")){msg(player,"no-permission",Map.of());return true;}if(args.length==0){msg(player,"usage",Map.of());return true;}return switch(args[0].toLowerCase(Locale.ROOT)){case "create"->{if(args.length!=2){msg(player,"usage",Map.of());yield true;}yield create(player,args[1]);}case "invite"->invite(player,args);case "accept"->accept(player,args);case "deny"->deny(player,args);case "list"->{new TeamGui(plugin).teams(player);yield true;}case "members"->members(player);case "kick"->kick(player,args);case "joinrequest","request"->request(player,args);case "acceptrequest"->acceptRequest(player,args);case "denyrequest"->denyRequest(player,args);case "settings"->settings(player);case "chat","tc"->chat(player,args);case "togglechat"->toggleChat(player);default->{msg(player,"usage",Map.of());yield true;}};}
  private boolean create(Player player,String name){if(!name.matches("[A-Za-z0-9]{2,10}")){msg(player,"invalid-name",Map.of());return true;}if(plugin.teams().teamOf(player.getUniqueId())!=null){msg(player,"already-in-team",Map.of());return true;}if(plugin.teams().nameTaken(name)){msg(player,"name-taken",Map.of());return true;}plugin.teams().create(name,player.getUniqueId());msg(player,"created",Map.of("team",name));return true;}
  private boolean invite(Player player,String[] args){Team team=leaderTeam(player);if(team==null)return true;if(team.members().size()>=plugin.getConfig().getInt("max-members",10)){msg(player,"team-full",Map.of());return true;}if(args.length!=2){msg(player,"usage",Map.of());return true;}Player target=Bukkit.getPlayerExact(args[1]);if(target==null){msg(player,"player-not-found",Map.of());return true;}if(plugin.teams().teamOf(target.getUniqueId())!=null){msg(player,"target-in-team",Map.of());return true;}long expires=System.currentTimeMillis()+plugin.getConfig().getLong("invite-duration-seconds",60)*1000;invites.put(target.getUniqueId(),new Invite(player.getUniqueId(),team.name(),expires));msg(player,"invited",Map.of("player",target.getName(),"team",team.name()));msg(target,"invite-received",Map.of("player",player.getName(),"team",team.name()));return true;}
  private boolean accept(Player player,String[] args){Invite invite=validInvite(player,args);if(invite==null)return true;Team team=plugin.teams().teamOf(invite.inviter());if(team==null||!team.name().equalsIgnoreCase(invite.team())){msg(player,"invite-expired",Map.of());return true;}if(!plugin.teams().addMember(team,player.getUniqueId(),plugin.getConfig().getInt("max-members",10))){msg(player,"team-full",Map.of());return true;}invites.remove(player.getUniqueId());joined(player,team);return true;}
  private boolean deny(Player player,String[] args){if(validInvite(player,args)==null)return true;invites.remove(player.getUniqueId());msg(player,"denied",Map.of());return true;}
  private Invite validInvite(Player player,String[] args){if(args.length!=2){msg(player,"usage",Map.of());return null;}Invite invite=invites.get(player.getUniqueId());if(invite==null||invite.expiresAt()<System.currentTimeMillis()){invites.remove(player.getUniqueId());msg(player,"invite-expired",Map.of());return null;}OfflinePlayer inviter=Bukkit.getOfflinePlayer(invite.inviter());if(inviter.getName()==null||!inviter.getName().equalsIgnoreCase(args[1])){msg(player,"invite-expired",Map.of());return null;}return invite;}
  private boolean request(Player player,String[] args){if(args.length!=2){msg(player,"usage",Map.of());return true;}Team team=plugin.teams().allTeams().stream().filter(t->t.name().equalsIgnoreCase(args[1])).findFirst().orElse(null);if(team==null){msg(player,"player-not-found",Map.of());return true;}return requestJoin(player,team);}
  public boolean requestJoin(Player player,Team team){if(plugin.teams().teamOf(player.getUniqueId())!=null){msg(player,"already-in-team",Map.of());return true;}if(team.members().size()>=plugin.getConfig().getInt("max-members",10)){msg(player,"team-full",Map.of());return true;}if(!team.joinRequestsEnabled()){msg(player,"join-requests-disabled",Map.of());return true;}requests.computeIfAbsent(team.name().toLowerCase(Locale.ROOT),ignored->new HashMap<>()).put(player.getUniqueId(),new Request(player.getUniqueId(),System.currentTimeMillis()+60_000));msg(player,"join-request-sent",Map.of("team",team.name()));Player leader=Bukkit.getPlayer(team.leader());if(leader!=null)msg(leader,"join-request-received",Map.of("player",player.getName()));return true;}
  private boolean acceptRequest(Player leader,String[] args){Team team=leaderTeam(leader);if(team==null)return true;Player target=requestPlayer(leader,team,args);if(target==null)return true;if(!plugin.teams().addMember(team,target.getUniqueId(),plugin.getConfig().getInt("max-members",10))){msg(leader,"team-full",Map.of());return true;}removeRequest(team,target.getUniqueId());msg(leader,"request-accepted",Map.of("player",target.getName()));joined(target,team);return true;}
  private boolean denyRequest(Player leader,String[] args){Team team=leaderTeam(leader);if(team==null)return true;Player target=requestPlayer(leader,team,args);if(target==null)return true;removeRequest(team,target.getUniqueId());msg(leader,"request-denied",Map.of());return true;}
  private Player requestPlayer(Player leader,Team team,String[] args){if(args.length!=2){msg(leader,"usage",Map.of());return null;}Player target=Bukkit.getPlayerExact(args[1]);Map<UUID,Request> pending=requests.get(team.name().toLowerCase(Locale.ROOT));if(target==null||pending==null||!pending.containsKey(target.getUniqueId())||pending.get(target.getUniqueId()).expiresAt()<System.currentTimeMillis()){msg(leader,"no-join-request",Map.of());return null;}return target;}
  private void removeRequest(Team team,UUID id){Map<UUID,Request> pending=requests.get(team.name().toLowerCase(Locale.ROOT));if(pending!=null)pending.remove(id);}
  private boolean members(Player player){Team team=plugin.teams().teamOf(player.getUniqueId());if(team==null){msg(player,"not-in-team",Map.of());return true;}new TeamGui(plugin).members(player,team);return true;}
  private boolean settings(Player player){Team team=leaderTeam(player);if(team==null)return true;new TeamGui(plugin).settings(player,team);return true;}
  private boolean chat(Player player,String[] args){Team team=plugin.teams().teamOf(player.getUniqueId());if(team==null){msg(player,"not-in-team",Map.of());return true;}if(!team.teamChatEnabled()){msg(player,"team-chat-disabled",Map.of());return true;}if(args.length<2){msg(player,"usage",Map.of());return true;}sendTeamChat(player,team,String.join(" ",Arrays.copyOfRange(args,1,args.length)));return true;}
  private boolean toggleChat(Player player){Team team=plugin.teams().teamOf(player.getUniqueId());if(team==null){msg(player,"not-in-team",Map.of());return true;}if(!team.teamChatEnabled()){msg(player,"team-chat-disabled",Map.of());return true;}if(teamChatUsers.remove(player.getUniqueId()))msg(player,"team-chat-toggled-off",Map.of());else{teamChatUsers.add(player.getUniqueId());msg(player,"team-chat-toggled-on",Map.of());}return true;}
  private void sendTeamChat(Player player,Team team,String text){for(UUID id:team.members()){Player member=Bukkit.getPlayer(id);if(member!=null)msg(member,"team-chat",Map.of("player",player.getName(),"message",text));}}
  private boolean kick(Player player,String[] args){Team team=leaderTeam(player);if(team==null)return true;if(args.length!=2){msg(player,"usage",Map.of());return true;}Player target=Bukkit.getPlayerExact(args[1]);if(target==null||!team.members().contains(target.getUniqueId())){msg(player,"player-not-found",Map.of());return true;}if(target.getUniqueId().equals(team.leader())){msg(player,"cannot-kick-leader",Map.of());return true;}plugin.teams().removeMember(team,target.getUniqueId());msg(player,"kicked",Map.of("player",target.getName()));msg(target,"kicked-target",Map.of("team",team.name()));return true;}
  private Team leaderTeam(Player player){Team team=plugin.teams().teamOf(player.getUniqueId());if(team==null){msg(player,"not-in-team",Map.of());return null;}if(!team.leader().equals(player.getUniqueId())){msg(player,"leader-only",Map.of());return null;}return team;}
  private void joined(Player player,Team team){msg(player,"accepted",Map.of("team",team.name()));for(UUID id:team.members()){Player member=Bukkit.getPlayer(id);if(member!=null&&!member.equals(player))msg(member,"member-joined",Map.of("player",player.getName()));}}
  public void send(CommandSender target,String key,Map<String,String> vars){msg(target,key,vars);}
  private void msg(CommandSender target,String key,Map<String,String> vars){String value=plugin.getConfig().getString("messages."+key,"");Map<String,String> all=new HashMap<>(vars);all.put("prefix",plugin.getConfig().getString("messages.prefix",""));all.put("duration",String.valueOf(plugin.getConfig().getLong("invite-duration-seconds",60)));for(var entry:all.entrySet())value=value.replace("%"+entry.getKey()+"%",entry.getValue());target.sendMessage(Text.component(value));}
  @Override public List<String> onTabComplete(CommandSender sender,Command command,String alias,String[] args){if(args.length==1)return List.of("create","invite","accept","deny","list","members","kick","joinrequest","acceptrequest","denyrequest","settings","chat","togglechat").stream().filter(s->s.startsWith(args[0].toLowerCase())).toList();if(args.length==2&&args[0].equalsIgnoreCase("joinrequest"))return plugin.teams().allTeams().stream().map(Team::name).filter(s->s.toLowerCase().startsWith(args[1].toLowerCase())).toList();if(args.length==2&&List.of("invite","kick","accept","deny","acceptrequest","denyrequest").contains(args[0].toLowerCase()))return Bukkit.getOnlinePlayers().stream().map(Player::getName).filter(s->s.toLowerCase().startsWith(args[1].toLowerCase())).toList();return List.of();}
}
