package me.semmmetje.banditteams.command;

import me.semmmetje.banditteams.BanditTeams;
import me.semmmetje.banditteams.storage.Team;
import me.semmmetje.banditteams.util.Text;
import org.bukkit.Bukkit;
import org.bukkit.OfflinePlayer;
import org.bukkit.command.*;
import org.bukkit.entity.Player;
import java.util.*;

public final class TeamCommand implements CommandExecutor, TabCompleter {
  private record Invite(UUID inviter, String team, long expiresAt){} private final BanditTeams plugin; private final Map<UUID,Invite> invites=new HashMap<>();
  public TeamCommand(BanditTeams plugin){this.plugin=plugin;}
  @Override public boolean onCommand(CommandSender sender,Command command,String label,String[] args){if(!(sender instanceof Player player)){msg(sender,"player-only",Map.of());return true;}if(!player.hasPermission("banditteams.use")){msg(player,"no-permission",Map.of());return true;}if(args.length==0){msg(player,"usage",Map.of());return true;}String sub=args[0].toLowerCase(Locale.ROOT);return switch(sub){case "create"->create(player,args);case "invite"->invite(player,args);case "accept"->accept(player,args);case "deny"->deny(player,args);case "list"->list(player);case "kick"->kick(player,args);default->{msg(player,"usage",Map.of());yield true;}};}
  private boolean create(Player player,String[] args){if(args.length!=2){msg(player,"usage",Map.of());return true;}String name=args[1];if(!name.matches("[A-Za-z0-9_-]{2,10}")){msg(player,"invalid-name",Map.of());return true;}if(plugin.teams().teamOf(player.getUniqueId())!=null){msg(player,"already-in-team",Map.of());return true;}if(plugin.teams().nameTaken(name)){msg(player,"name-taken",Map.of());return true;}plugin.teams().create(name,player.getUniqueId());msg(player,"created",Map.of("team",name));return true;}
  private boolean invite(Player player,String[] args){Team team=leaderTeam(player);if(team==null)return true;if(args.length!=2){msg(player,"usage",Map.of());return true;}Player target=Bukkit.getPlayerExact(args[1]);if(target==null){msg(player,"player-not-found",Map.of());return true;}if(plugin.teams().teamOf(target.getUniqueId())!=null){msg(player,"target-in-team",Map.of());return true;}long expires=System.currentTimeMillis()+plugin.getConfig().getLong("invite-duration-seconds",60)*1000;invites.put(target.getUniqueId(),new Invite(player.getUniqueId(),team.name(),expires));msg(player,"invited",Map.of("player",target.getName(),"team",team.name()));msg(target,"invite-received",Map.of("player",player.getName(),"team",team.name()));return true;}
  private boolean accept(Player player,String[] args){Invite invite=validInvite(player,args);if(invite==null)return true;Team team=plugin.teams().teamOf(invite.inviter());if(team==null||!team.name().equalsIgnoreCase(invite.team())||!plugin.teams().addMember(team,player.getUniqueId())){msg(player,"invite-expired",Map.of());return true;}invites.remove(player.getUniqueId());msg(player,"accepted",Map.of("team",team.name()));for(UUID id:team.members()){Player member=Bukkit.getPlayer(id);if(member!=null&&!member.equals(player))msg(member,"member-joined",Map.of("player",player.getName()));}return true;}
  private boolean deny(Player player,String[] args){Invite invite=validInvite(player,args);if(invite==null)return true;invites.remove(player.getUniqueId());msg(player,"denied",Map.of());return true;}
  private Invite validInvite(Player player,String[] args){if(args.length!=2){msg(player,"usage",Map.of());return null;}Invite invite=invites.get(player.getUniqueId());if(invite==null||invite.expiresAt()<System.currentTimeMillis()){invites.remove(player.getUniqueId());msg(player,"invite-expired",Map.of());return null;}OfflinePlayer inviter=Bukkit.getOfflinePlayer(invite.inviter());if(inviter.getName()==null||!inviter.getName().equalsIgnoreCase(args[1])){msg(player,"invite-expired",Map.of());return null;}return invite;}
  private boolean list(Player player){Team team=plugin.teams().teamOf(player.getUniqueId());if(team==null){msg(player,"not-in-team",Map.of());return true;}String leader=name(team.leader());String members=team.members().stream().map(this::name).sorted().reduce((a,b)->a+", "+b).orElse("-");msg(player,"list",Map.of("team",team.name(),"leader",leader,"members",members));return true;}
  private boolean kick(Player player,String[] args){Team team=leaderTeam(player);if(team==null)return true;if(args.length!=2){msg(player,"usage",Map.of());return true;}Player target=Bukkit.getPlayerExact(args[1]);if(target==null||!team.members().contains(target.getUniqueId())){msg(player,"player-not-found",Map.of());return true;}if(target.getUniqueId().equals(team.leader())){msg(player,"cannot-kick-leader",Map.of());return true;}plugin.teams().removeMember(team,target.getUniqueId());msg(player,"kicked",Map.of("player",target.getName()));msg(target,"kicked-target",Map.of("team",team.name()));return true;}
  private Team leaderTeam(Player player){Team team=plugin.teams().teamOf(player.getUniqueId());if(team==null){msg(player,"not-in-team",Map.of());return null;}if(!team.leader().equals(player.getUniqueId())){msg(player,"leader-only",Map.of());return null;}return team;}
  private String name(UUID id){OfflinePlayer player=Bukkit.getOfflinePlayer(id);return player.getName()==null?id.toString().substring(0,8):player.getName();}
  private void msg(CommandSender target,String key,Map<String,String> vars){String value=plugin.getConfig().getString("messages."+key,"");Map<String,String> all=new HashMap<>(vars);all.put("prefix",plugin.getConfig().getString("messages.prefix",""));all.put("duration",String.valueOf(plugin.getConfig().getLong("invite-duration-seconds",60)));for(var entry:all.entrySet())value=value.replace("%"+entry.getKey()+"%",entry.getValue());target.sendMessage(Text.component(value));}
  @Override public List<String> onTabComplete(CommandSender sender,Command command,String alias,String[] args){if(args.length==1)return List.of("create","invite","accept","deny","list","kick").stream().filter(s->s.startsWith(args[0].toLowerCase())).toList();if(args.length==2&&List.of("invite","kick","accept","deny").contains(args[0].toLowerCase()))return Bukkit.getOnlinePlayers().stream().map(Player::getName).filter(s->s.toLowerCase().startsWith(args[1].toLowerCase())).toList();return List.of();}
}
