name: BanditTeams
version: 1.1.0
main: me.semmmetje.banditteams.BanditTeams
api-version: '1.21'
author: Semmmetje
softdepend: [PlaceholderAPI]
commands:
  banditteams:
    description: Reload BanditTeams
    usage: /banditteams reload
permissions:
  banditteams.use:
    default: true
  banditteams.admin:
    default: op
